name: 'dbdesign '
favicon: null
layout_spectrum: 1
typography_spectrum: 0.8340931
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: Concepts
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#010101'
    - '#F2F2F2'
    - '#655442'
    - '#CFCFCF'
    - '#898989'
  brandStrength: 0.9877753
  lightness: 0.9923511
  saturation: 0.9434429
  rhythmicContrast: 0.6050866
purpose: []
